var SnarkRouteAE = (function () {
  function result(value) { return JSON.stringify({ ok: true, value: value }); }
  function failure(error) { return JSON.stringify({ ok: false, error: error && error.message ? error.message : String(error) }); }
  function comp() { if (!(app.project && app.project.activeItem instanceof CompItem)) throw new Error("Open an active composition first."); return app.project.activeItem; }
  function itemById(id) { for (var i = 1; i <= app.project.numItems; i++) if (app.project.item(i).id === id) return app.project.item(i); throw new Error("Placeholder footage item is no longer available."); }
  function ensureFolder(path) { var folder = new Folder(path); if (!folder.exists && !folder.create()) throw new Error("Could not create folder: " + path); return folder; }
  function metadataText(metadata) { return "SnarkRoute jobId=" + metadata.jobId + "; modelId=" + metadata.modelId + "; manifest=" + metadata.manifestPath; }
  return {
    getActiveComposition: function () { try { var active = app.project && app.project.activeItem; return result(active instanceof CompItem ? { id: active.id, name: active.name } : null); } catch (e) { return failure(e); } },
    getCurrentFrameSource: function () { try { var active = comp(); var folder = ensureFolder(Folder.temp.fsName + "/SnarkRoute AE"); var file = new File(folder.fsName + "/frame-" + (new Date().getTime()) + ".png"); active.saveFrameToPng(active.time, file); return result({ path: file.fsName, filename: file.name, width: active.width, height: active.height, frameRate: active.frameRate, duration: active.duration }); } catch (e) { return failure(e); } },
    createGenerationPlaceholder: function (spec) { try { app.beginUndoGroup("SnarkRoute generation placeholder"); var active = comp(); var duration = Math.max(1 / active.frameRate, Number(spec.duration) || 5); var footage = app.project.importPlaceholder(spec.name, active.width, active.height, active.frameRate, duration); var layer = active.layers.add(footage); layer.startTime = active.time; layer.name = spec.name; var reference = { compositionId: active.id, layerIndex: layer.index, footageItemId: footage.id }; app.endUndoGroup(); return result(reference); } catch (e) { try { app.endUndoGroup(); } catch (_) {} return failure(e); } },
    replacePlaceholderSource: function (reference, resultPath) { try { app.beginUndoGroup("Replace SnarkRoute placeholder"); var footage = itemById(reference.footageItemId); footage.replace(new File(resultPath)); var folderName = "SnarkRoute Generations"; var projectFolder = null; for (var i = 1; i <= app.project.numItems; i++) { var candidate = app.project.item(i); if (candidate instanceof FolderItem && candidate.name === folderName) { projectFolder = candidate; break; } } if (!projectFolder) projectFolder = app.project.items.addFolder(folderName); footage.parentFolder = projectFolder; app.endUndoGroup(); return result(null); } catch (e) { try { app.endUndoGroup(); } catch (_) {} return failure(e); } },
    writeGenerationMetadata: function (reference, metadata) { try { var active = comp(); var layer = active.layer(reference.layerIndex); if (!layer || layer.source.id !== reference.footageItemId) throw new Error("Generated layer reference changed before metadata could be written."); layer.comment = metadataText(metadata); var marker = new MarkerValue(metadataText(metadata)); layer.property("Marker").setValueAtTime(0, marker); return result(null); } catch (e) { return failure(e); } },
    generationDirectory: function () { try { var base = app.project.file ? app.project.file.parent.fsName : Folder.userData.fsName; return result(ensureFolder(base + "/SnarkRoute Generations").fsName); } catch (e) { return failure(e); } },
    revealFile: function (path) { try { var file = new File(path); if (!file.exists) throw new Error("Output file no longer exists."); file.parent.execute(); return result(null); } catch (e) { return failure(e); } }
  };
}());
