var SnarkRouteAE = (function () {
  function result(value) { return JSON.stringify({ ok: true, value: value }); }
  function failure(error) { return JSON.stringify({ ok: false, error: error && error.message ? error.message : String(error) }); }
  function comp() { if (!(app.project && app.project.activeItem instanceof CompItem)) throw new Error("Open an active composition first."); return app.project.activeItem; }
  function itemById(id) { for (var i = 1; i <= app.project.numItems; i++) if (app.project.item(i).id === id) return app.project.item(i); throw new Error("Placeholder footage item is no longer available."); }
  function compositionById(id) { var item = itemById(id); if (!(item instanceof CompItem)) throw new Error("Source composition is no longer available."); return item; }
  function ensureFolder(path) { var folder = new Folder(path); if (!folder.exists && !folder.create()) throw new Error("Could not create folder: " + path); return folder; }
  function metadataText(metadata) { return "SnarkRoute jobId=" + metadata.jobId + "; modelId=" + metadata.modelId + "; manifest=" + metadata.manifestPath; }
  function exportFailure(path, fileError) { return new Error("Current frame export failed\nPath: " + (path || "unknown") + "\nFile.error: " + (fileError || "unknown")); }
  function inspectReadableFile(path) { var inspected = new File(path); var state = { path: inspected.fsName || path, exists: inspected.exists, size: 0, readable: false, fileError: inspected.error || "" }; if (!state.exists) return state; state.size = Number(inspected.length) || 0; if (state.size <= 0) return state; inspected.encoding = "BINARY"; if (!inspected.open("r")) { state.fileError = inspected.error || "File cannot be opened for reading."; return state; } var probe = inspected.read(1); state.fileError = inspected.error || ""; inspected.close(); state.readable = Boolean(probe && probe.length > 0 && !state.fileError); return state; }
  function waitForStableReadableFile(path, timeoutMs, intervalMs) { var startedAt = new Date().getTime(); var attempts = 0; var stableChecks = 0; var previousSize = -1; var state = inspectReadableFile(path); while (true) { attempts++; state = inspectReadableFile(path); if (state.exists && state.size > 0 && state.readable) { stableChecks = state.size === previousSize ? stableChecks + 1 : 1; if (stableChecks >= 2) return { ok: true, state: state, attempts: attempts, waitedMs: new Date().getTime() - startedAt }; } else { stableChecks = 0; } previousSize = state.size > 0 ? state.size : -1; var waitedMs = new Date().getTime() - startedAt; if (waitedMs >= timeoutMs) return { ok: false, state: state, attempts: attempts, waitedMs: waitedMs }; $.sleep(Math.min(intervalMs, timeoutMs - waitedMs)); } }
  function frameExportResult(ok, file, wait, fileError, fallbackAttempted, removedZeroByteFile) { return { ok: ok, stage: "exporting_current_frame", exportMethod: "saveFrameToPng", path: file ? file.fsName : "unknown", filename: file ? file.name : "", exists: wait && wait.state ? wait.state.exists : false, size: wait && wait.state ? wait.state.size : 0, waitedMs: wait ? wait.waitedMs : 0, attempts: wait ? wait.attempts : 0, fileError: fileError || (wait && wait.state ? wait.state.fileError : ""), fallbackAttempted: fallbackAttempted, removedZeroByteFile: removedZeroByteFile }; }
  function renderCurrentFrameWithRenderQueueFallback(snapshot, path) { return null; }
  return {
    getActiveComposition: function () { try { var active = app.project && app.project.activeItem; return result(active instanceof CompItem ? { id: active.id, name: active.name, time: active.time, width: active.width, height: active.height, frameRate: active.frameRate, duration: active.duration, pixelAspect: active.pixelAspect } : null); } catch (e) { return failure(e); } },
    renderCurrentFrame: function (snapshot) { var file = null; try { var active = comp(); if (active.id !== snapshot.id) return result(frameExportResult(false, file, null, "Active composition changed before export.", false, false)); if (Math.abs(active.time - snapshot.time) > (1 / Math.max(active.frameRate, 1)) / 100) return result(frameExportResult(false, file, null, "Composition time changed before export.", false, false)); var folder = ensureFolder(Folder.temp.fsName + "/SnarkRoute AE"); file = new File(folder.fsName + "/frame-" + (new Date().getTime()) + "-" + Math.floor(Math.random() * 1000000000) + ".png"); active.saveFrameToPng(snapshot.time, file); var wait = waitForStableReadableFile(file.fsName, 10000, 150); if (wait.ok) return result(frameExportResult(true, file, wait, "", false, false)); var removed = false; if (wait.state.exists && wait.state.size <= 0) { var emptyFile = new File(file.fsName); removed = emptyFile.remove(); if (!removed && emptyFile.error) wait.state.fileError = emptyFile.error; } var fallback = renderCurrentFrameWithRenderQueueFallback(snapshot, file.fsName); if (fallback) return result(fallback); return result(frameExportResult(false, file, wait, wait.state.fileError || "Timed out waiting for saveFrameToPng. Render Queue fallback is not enabled.", false, removed)); } catch (e) { return result(frameExportResult(false, file, null, file && file.error ? file.error : (e && e.message ? e.message : String(e)), false, false)); } },
    validateInputFile: function (path) { var file = new File(path); try { var absolute = file.fsName; if (!absolute || !(/^[A-Za-z]:[\\\/]/.test(absolute) || /^\\\\/.test(absolute) || /^\//.test(absolute))) throw exportFailure(path, "Export path is not absolute."); var inspected = inspectReadableFile(absolute); if (!inspected.exists) throw exportFailure(absolute, inspected.fileError || "File does not exist."); if (inspected.size <= 0) throw exportFailure(absolute, inspected.fileError || "File is empty."); if (!inspected.readable) throw exportFailure(absolute, inspected.fileError || "File cannot be read."); return result({ path: absolute, sizeBytes: inspected.size, fileError: "" }); } catch (e) { return failure(e && e.message && e.message.indexOf("Current frame export failed") === 0 ? e : exportFailure(file.fsName || path, file.error || (e && e.message))); } },
    createGenerationPlaceholder: function (spec) { try { app.beginUndoGroup("SnarkRoute generation placeholder"); var target = compositionById(spec.compositionId); var duration = Math.max(1 / spec.frameRate, Number(spec.duration) || 5); var layer = target.layers.addSolid([0.12, 0.12, 0.12], spec.name, spec.width, spec.height, spec.pixelAspect || 1, duration); var footage = layer.source; try { footage.mainSource.conformFrameRate = spec.frameRate; } catch (_) {} layer.startTime = spec.sourceTime; layer.inPoint = spec.sourceTime; layer.outPoint = Math.min(target.duration, spec.sourceTime + duration); layer.name = spec.name; var reference = { compositionId: target.id, layerIndex: layer.index, footageItemId: footage.id }; app.endUndoGroup(); return result(reference); } catch (e) { try { app.endUndoGroup(); } catch (_) {} return failure(e); } },
    replacePlaceholderSource: function (reference, resultPath) { try { app.beginUndoGroup("Replace SnarkRoute placeholder"); var footage = itemById(reference.footageItemId); footage.replace(new File(resultPath)); var folderName = "SnarkRoute Generations"; var projectFolder = null; for (var i = 1; i <= app.project.numItems; i++) { var candidate = app.project.item(i); if (candidate instanceof FolderItem && candidate.name === folderName) { projectFolder = candidate; break; } } if (!projectFolder) projectFolder = app.project.items.addFolder(folderName); footage.parentFolder = projectFolder; app.endUndoGroup(); return result(null); } catch (e) { try { app.endUndoGroup(); } catch (_) {} return failure(e); } },
    writeGenerationMetadata: function (reference, metadata) { try { var target = compositionById(reference.compositionId); var layer = target.layer(reference.layerIndex); if (!layer || layer.source.id !== reference.footageItemId) throw new Error("Generated layer reference changed before metadata could be written."); layer.comment = metadataText(metadata); var marker = new MarkerValue(metadataText(metadata)); layer.property("Marker").setValueAtTime(0, marker); return result(null); } catch (e) { return failure(e); } },
    generationDirectory: function () { try { var base = app.project.file ? app.project.file.parent.fsName : Folder.userData.fsName; return result(ensureFolder(base + "/SnarkRoute Generations").fsName); } catch (e) { return failure(e); } },
    revealFile: function (path) { try { var file = new File(path); if (!file.exists) throw new Error("File no longer exists: " + path); file.parent.execute(); return result(null); } catch (e) { return failure(e); } },
    openFile: function (path) { try { var file = new File(path); if (!file.exists) throw new Error("File no longer exists: " + path); if (!file.execute()) throw new Error(file.error || "Could not open file: " + path); return result(null); } catch (e) { return failure(e); } }
  };
}());
