var SnarkRouteAE = (function () {
  function result(value) { return JSON.stringify({ ok: true, value: value }); }
  function failure(error) { return JSON.stringify({ ok: false, error: error && error.message ? error.message : String(error) }); }
  function comp() { if (!(app.project && app.project.activeItem instanceof CompItem)) throw new Error("Open an active composition first."); return app.project.activeItem; }
  function itemById(id) { for (var i = 1; i <= app.project.numItems; i++) if (app.project.item(i).id === id) return app.project.item(i); throw new Error("Placeholder footage item is no longer available."); }
  function compositionById(id) { var item = itemById(id); if (!(item instanceof CompItem)) throw new Error("Source composition is no longer available."); return item; }
  function sourceType(source) { if (!source) return "none"; if (typeof FileSource !== "undefined" && source.mainSource instanceof FileSource) return "FileSource"; if (typeof SolidSource !== "undefined" && source.mainSource instanceof SolidSource) return "SolidSource"; return source.mainSource && source.mainSource.constructor ? source.mainSource.constructor.name : "unknown"; }
  function projectFolder(name) { for (var i = 1; i <= app.project.numItems; i++) { var candidate = app.project.item(i); if (candidate instanceof FolderItem && candidate.name === name) return candidate; } return app.project.items.addFolder(name); }
  function generationSubfolder(name) { var root = projectFolder("SnarkRoute Generations"); for (var i = 1; i <= app.project.numItems; i++) { var candidate = app.project.item(i); if (candidate instanceof FolderItem && candidate.name === name && candidate.parentFolder && candidate.parentFolder.id === root.id) return candidate; } var folder = app.project.items.addFolder(name); folder.parentFolder = root; return folder; }
  function generationFolder(mediaKind) { return generationSubfolder(mediaKind === "image" ? "Images" : "Videos"); }
  function jobComment(jobId, modelId, role) { return "SnarkRoute job:" + jobId + (modelId ? " model:" + modelId : "") + " role:" + role; }
  function layerHasJobId(layer, jobId) { var comment = String(layer && layer.comment || ""); return Boolean(layer && jobId && (comment.indexOf("job:" + jobId) >= 0 || comment.indexOf("jobId=" + jobId) >= 0)); }
  function layerHasRole(layer, role) { return String(layer && layer.comment || "").indexOf("role:" + role) >= 0; }
  function findPlaceholderLayer(reference) { var target = compositionById(reference.compositionId); var hint = null; try { hint = reference.layerIndex ? target.layer(reference.layerIndex) : null; } catch (_) {} if (hint && layerHasJobId(hint, reference.jobId) && (layerHasRole(hint, "placeholder") || String(hint.comment || "").indexOf("placeholder=true") >= 0)) return hint; for (var i = 1; i <= target.numLayers; i++) { var layer = target.layer(i); if (layerHasJobId(layer, reference.jobId) && (layerHasRole(layer, "placeholder") || String(layer.comment || "").indexOf("placeholder=true") >= 0)) return layer; } return null; }
  function removeJobOverlays(target, jobId) { var removed = 0; for (var i = target.numLayers; i >= 1; i--) { var layer = target.layer(i); if (layerHasJobId(layer, jobId) && layerHasRole(layer, "overlay")) { layer.remove(); removed++; } } return removed; }
  function supportedMediaPath(path, mediaKind) { return mediaKind === "image" ? /\.(png|jpe?g|webp|tiff?)$/i.test(path) : /\.(mp4|mov|m4v|avi|mxf|webm)$/i.test(path); }
  function importedFootageForPath(path) { for (var i = 1; i <= app.project.numItems; i++) { var item = app.project.item(i); try { if (item instanceof FootageItem && item.mainSource instanceof FileSource && item.mainSource.file && item.mainSource.file.fsName === path) return item; } catch (_) {} } return null; }
  function importPlaceholderPreview(path, kind) { var state = inspectReadableFile(path); if (!state.exists || state.size <= 0 || !state.readable) throw new Error(state.fileError || "Placeholder preview is missing, empty, or unreadable."); if (!supportedMediaPath(state.path, kind === "video" ? "video" : "image")) throw new Error("Unsupported placeholder preview: " + state.path); var options = new ImportOptions(new File(state.path)); if (options.canImportAs && !options.canImportAs(ImportAsType.FOOTAGE)) throw new Error("After Effects cannot import the placeholder preview as footage."); try { options.importAs = ImportAsType.FOOTAGE; } catch (_) {} var imported = app.project.importFile(options); if (!(imported instanceof FootageItem) || !(imported.mainSource instanceof FileSource)) throw new Error("Placeholder preview import did not return FileSource footage."); imported.parentFolder = generationSubfolder("Placeholders"); return imported; }
  function setLayerTiming(layer, sourceTime, duration, targetDuration) { layer.startTime = sourceTime; layer.inPoint = sourceTime; layer.outPoint = Math.min(targetDuration, sourceTime + duration); }
  function clamp(value, minimum, maximum) { return Math.max(minimum, Math.min(maximum, value)); }
  function setStaticProperty(property, value) { while (property.numKeys > 0) property.removeKey(property.numKeys); try { if (property.canSetExpression) property.expression = ""; } catch (_) {} try { property.expressionEnabled = false; } catch (_) {} property.setValue(value); }
  function prepareOverlayLayer(layer) { layer.enabled = true; layer.shy = false; layer.guideLayer = false; try { layer.threeDLayer = false; } catch (_) {} try { layer.parent = null; } catch (_) {} try { if (typeof TrackMatteType !== "undefined") layer.trackMatteType = TrackMatteType.NO_TRACK_MATTE; } catch (_) {} var transform = layer.property("ADBE Transform Group"); setStaticProperty(transform.property("ADBE Scale"), [100, 100]); setStaticProperty(transform.property("ADBE Opacity"), 100); return transform; }
  function createGenerationOverlay(target, spec, duration, placeholderLayer) { var textLayer = null, diagnostics = { compWidth: target.width, compHeight: target.height }; try { textLayer = target.layers.addText("Generating…"); textLayer.name = "SnarkRoute · Generating text"; textLayer.comment = jobComment(spec.jobId, spec.modelId, "overlay"); setLayerTiming(textLayer, spec.sourceTime, duration, target.duration); var textTransform = prepareOverlayLayer(textLayer); var fontSize = clamp(target.height * 0.06, 36, 110); var sourceText = textLayer.property("Source Text"); var documentValue = sourceText.value; documentValue.text = "Generating…"; documentValue.fontSize = fontSize; documentValue.applyFill = true; documentValue.fillColor = [1, 1, 1]; documentValue.applyStroke = false; if (typeof ParagraphJustification !== "undefined") documentValue.justification = ParagraphJustification.CENTER_JUSTIFY; sourceText.setValue(documentValue); var bounds = textLayer.sourceRectAtTime(target.time, false); diagnostics.fontSize = fontSize; diagnostics.sourceRect = { left: bounds.left, top: bounds.top, width: bounds.width, height: bounds.height }; if (!(bounds.width > 0) || !(bounds.height > 0)) throw new Error("Generating overlay sourceRectAtTime returned empty bounds."); var position = [target.width * 0.5, target.height * 0.9]; var anchorPoint = [bounds.left + bounds.width / 2, bounds.top + bounds.height]; textTransform.property("ADBE Anchor Point").setValue(anchorPoint); textTransform.property("ADBE Position").setValue(position); try { textLayer.moveBefore(placeholderLayer); } catch (_) {} var opacity = textTransform.property("ADBE Opacity"); diagnostics.anchorPoint = anchorPoint; diagnostics.position = position; diagnostics.scale = textTransform.property("ADBE Scale").value; diagnostics.opacity = opacity.value; diagnostics.opacityKeyframes = opacity.numKeys; diagnostics.opacityExpression = opacity.expression || ""; diagnostics.textLayerIndex = textLayer.index; diagnostics.placeholderLayerIndex = placeholderLayer.index; return { error: "", diagnostics: diagnostics }; } catch (error) { try { if (textLayer) textLayer.remove(); } catch (_) {} return { error: error && error.message ? error.message : String(error), diagnostics: diagnostics }; } }
  function safeTemporaryPreviewFile(path) { if (!path || !Folder.temp) return null; var file = new File(path); var tempRoot = String(Folder.temp.fsName || "").replace(/\\/g, "/").toLowerCase(); var candidate = String(file.fsName || path).replace(/\\/g, "/").toLowerCase(); return candidate.indexOf(tempRoot + "/snarkroute ae/") === 0 ? file : null; }
  function ensureFolder(path) { var folder = new Folder(path); if (!folder.exists && !folder.create()) throw new Error("Could not create folder: " + path); return folder; }
  function metadataText(metadata) { return jobComment(metadata.jobId, metadata.modelId, "placeholder") + (metadata.manifestPath ? " manifest:" + metadata.manifestPath : ""); }
  function exportFailure(path, fileError) { return new Error("Current frame export failed\nPath: " + (path || "unknown") + "\nFile.error: " + (fileError || "unknown")); }
  function inspectReadableFile(path) { var inspected = new File(path); var state = { path: inspected.fsName || path, exists: inspected.exists, size: 0, readable: false, fileError: inspected.error || "" }; if (!state.exists) return state; state.size = Number(inspected.length) || 0; if (state.size <= 0) return state; inspected.encoding = "BINARY"; if (!inspected.open("r")) { state.fileError = inspected.error || "File cannot be opened for reading."; return state; } var probe = inspected.read(1); state.fileError = inspected.error || ""; inspected.close(); state.readable = Boolean(probe && probe.length > 0 && !state.fileError); return state; }
  function waitForStableReadableFile(path, timeoutMs, intervalMs) { var startedAt = new Date().getTime(); var attempts = 0; var stableChecks = 0; var previousSize = -1; var state = inspectReadableFile(path); while (true) { attempts++; state = inspectReadableFile(path); if (state.exists && state.size > 0 && state.readable) { stableChecks = state.size === previousSize ? stableChecks + 1 : 1; if (stableChecks >= 2) return { ok: true, state: state, attempts: attempts, waitedMs: new Date().getTime() - startedAt }; } else { stableChecks = 0; } previousSize = state.size > 0 ? state.size : -1; var waitedMs = new Date().getTime() - startedAt; if (waitedMs >= timeoutMs) return { ok: false, state: state, attempts: attempts, waitedMs: waitedMs }; $.sleep(Math.min(intervalMs, timeoutMs - waitedMs)); } }
  function frameExportResult(ok, file, wait, fileError, fallbackAttempted, removedZeroByteFile) { return { ok: ok, stage: "exporting_current_frame", exportMethod: "saveFrameToPng", path: file ? file.fsName : "unknown", filename: file ? file.name : "", exists: wait && wait.state ? wait.state.exists : false, size: wait && wait.state ? wait.state.size : 0, waitedMs: wait ? wait.waitedMs : 0, attempts: wait ? wait.attempts : 0, fileError: fileError || (wait && wait.state ? wait.state.fileError : ""), fallbackAttempted: fallbackAttempted, removedZeroByteFile: removedZeroByteFile }; }
  function renderCurrentFrameWithRenderQueueFallback(snapshot, path) { return null; }
  return {
    getActiveComposition: function () { try { var active = app.project && app.project.activeItem; return result(active instanceof CompItem ? { id: active.id, name: active.name, time: active.time, width: active.width, height: active.height, frameRate: active.frameRate, duration: active.duration, pixelAspect: active.pixelAspect } : null); } catch (e) { return failure(e); } },
    selectExternalImage: function () { try { var file = File.openDialog("Choose source image", "Images:*.png;*.jpg;*.jpeg;*.webp;*.tif;*.tiff", false); return result(file ? file.fsName : null); } catch (e) { return failure(e); } },
    selectExternalFile: function (kind) { try { var filter = kind === "audio" ? "Audio:*.wav;*.mp3;*.m4a;*.aac;*.flac" : kind === "video" ? "Video:*.mp4;*.mov;*.m4v;*.avi;*.mxf;*.webm" : "Images:*.png;*.jpg;*.jpeg;*.webp;*.tif;*.tiff"; var file = File.openDialog("Choose " + kind + " input", filter, false); return result(file ? file.fsName : null); } catch (e) { return failure(e); } },
    renderCompositionAudio: function () { return failure(new Error("Composition work area audio is planned but not implemented.")); },
    renderSelectedAudioLayer: function () { return failure(new Error("Selected audio layer rendering is planned but not implemented.")); },
    renderCurrentFrame: function (snapshot) { var file = null; try { var active = comp(); if (active.id !== snapshot.id) return result(frameExportResult(false, file, null, "Active composition changed before export.", false, false)); if (Math.abs(active.time - snapshot.time) > (1 / Math.max(active.frameRate, 1)) / 100) return result(frameExportResult(false, file, null, "Composition time changed before export.", false, false)); var folder = ensureFolder(Folder.temp.fsName + "/SnarkRoute AE"); file = new File(folder.fsName + "/frame-" + (new Date().getTime()) + "-" + Math.floor(Math.random() * 1000000000) + ".png"); active.saveFrameToPng(snapshot.time, file); var wait = waitForStableReadableFile(file.fsName, 10000, 150); if (wait.ok) return result(frameExportResult(true, file, wait, "", false, false)); var removed = false; if (wait.state.exists && wait.state.size <= 0) { var emptyFile = new File(file.fsName); removed = emptyFile.remove(); if (!removed && emptyFile.error) wait.state.fileError = emptyFile.error; } var fallback = renderCurrentFrameWithRenderQueueFallback(snapshot, file.fsName); if (fallback) return result(fallback); return result(frameExportResult(false, file, wait, wait.state.fileError || "Timed out waiting for saveFrameToPng. Render Queue fallback is not enabled.", false, removed)); } catch (e) { return result(frameExportResult(false, file, null, file && file.error ? file.error : (e && e.message ? e.message : String(e)), false, false)); } },
    validateInputFile: function (path) { var file = new File(path); try { var absolute = file.fsName; if (!absolute || !(/^[A-Za-z]:[\\\/]/.test(absolute) || /^\\\\/.test(absolute) || /^\//.test(absolute))) throw exportFailure(path, "Export path is not absolute."); var inspected = inspectReadableFile(absolute); if (!inspected.exists) throw exportFailure(absolute, inspected.fileError || "File does not exist."); if (inspected.size <= 0) throw exportFailure(absolute, inspected.fileError || "File is empty."); if (!inspected.readable) throw exportFailure(absolute, inspected.fileError || "File cannot be read."); return result({ path: absolute, sizeBytes: inspected.size, fileError: "" }); } catch (e) { return failure(e && e.message && e.message.indexOf("Current frame export failed") === 0 ? e : exportFailure(file.fsName || path, file.error || (e && e.message))); } },
    createGenerationPlaceholder: function (spec) { try { app.beginUndoGroup("SnarkRoute generation placeholder"); var target = compositionById(spec.compositionId); var duration = Math.max(1 / spec.frameRate, Number(spec.duration) || 5); var layer = null, footage = null, previewError = "", placeholderKind = "solid-fallback"; if (spec.previewPath && spec.previewKind !== "audio") { try { var preview = importPlaceholderPreview(spec.previewPath, spec.previewKind); layer = target.layers.add(preview); footage = preview; placeholderKind = "source-preview"; } catch (previewFailure) { previewError = previewFailure && previewFailure.message ? previewFailure.message : String(previewFailure); } } if (!layer) { layer = target.layers.addSolid([0.12, 0.12, 0.12], spec.name, spec.width, spec.height, spec.pixelAspect || 1, duration); footage = layer.source; try { footage.mainSource.conformFrameRate = spec.frameRate; } catch (_) {} } setLayerTiming(layer, spec.sourceTime, duration, target.duration); layer.name = spec.name; layer.comment = jobComment(spec.jobId, spec.modelId, "placeholder"); var overlay = createGenerationOverlay(target, spec, duration, layer); var overlayError = overlay.error; var reference = { compositionId: target.id, layerIndex: layer.index, footageItemId: footage.id, jobId: spec.jobId, previewPath: placeholderKind === "source-preview" ? spec.previewPath : undefined, previewTemporary: placeholderKind === "source-preview" && spec.previewTemporary === true, previewError: previewError || undefined, placeholderKind: placeholderKind, overlayCreated: !overlayError, overlayError: overlayError || undefined, overlayDiagnostics: overlay.diagnostics }; app.endUndoGroup(); return result(reference); } catch (e) { try { app.endUndoGroup(); } catch (_) {} return failure(e); } },
    importResultFootage: function (resultPath, itemName, mediaKind) { var imported = null; mediaKind = mediaKind === "image" ? "image" : "video"; var diagnostic = { ok: false, resultPath: resultPath, resultFileSize: 0, mediaKind: mediaKind }; try { var state = inspectReadableFile(resultPath); diagnostic.resultPath = state.path; diagnostic.resultFileSize = state.size; if (!state.exists || state.size <= 0 || !state.readable) throw new Error(state.fileError || "Downloaded result is missing, empty, or unreadable."); if (!supportedMediaPath(state.path, mediaKind)) throw new Error("Unsupported " + mediaKind + " extension: " + state.path); imported = importedFootageForPath(state.path); if (!imported) { var options = new ImportOptions(new File(state.path)); if (options.canImportAs && !options.canImportAs(ImportAsType.FOOTAGE)) throw new Error("After Effects cannot import the result as footage."); try { options.importAs = ImportAsType.FOOTAGE; } catch (_) {} imported = app.project.importFile(options); } if (!imported || !(imported instanceof FootageItem)) throw new Error("After Effects import did not return a FootageItem."); if (!(imported.mainSource instanceof FileSource)) throw new Error("Imported result does not use FileSource."); var folder = generationFolder(mediaKind); imported.parentFolder = folder; imported.name = itemName; diagnostic.ok = true; diagnostic.importedItemId = imported.id; diagnostic.importedItemName = imported.name; diagnostic.importedItemType = "FootageItem"; diagnostic.importedItemSourceType = sourceType(imported); diagnostic.duration = Number(imported.duration) || 0; diagnostic.width = Number(imported.width) || 0; diagnostic.height = Number(imported.height) || 0; diagnostic.projectFolderId = folder.id; diagnostic.projectFolderName = "SnarkRoute Generations/" + folder.name; return result(diagnostic); } catch (e) { diagnostic.importedItemId = imported ? imported.id : undefined; diagnostic.importedItemName = imported ? imported.name : undefined; diagnostic.importError = e && e.message ? e.message : String(e); return result(diagnostic); } },
    replacePlaceholderSource: function (reference, importedItemId, completedLayerName) { var diagnostic = { ok: false, sourceReplaced: false, placeholderDeleted: false, placeholderCompositionId: reference.compositionId }; try { var imported = itemById(importedItemId); if (!(imported instanceof FootageItem) || !(imported.mainSource instanceof FileSource)) throw new Error("Replacement item is not FileSource footage."); var target = compositionById(reference.compositionId); var layer = findPlaceholderLayer(reference); app.beginUndoGroup("Replace SnarkRoute placeholder"); if (!layer) { diagnostic.ok = true; diagnostic.placeholderDeleted = true; diagnostic.newSourceId = imported.id; diagnostic.newSourceType = sourceType(imported); diagnostic.overlayLayersRemoved = removeJobOverlays(target, reference.jobId); app.endUndoGroup(); return result(diagnostic); } var oldSource = layer.source; var temporaryPreviewFile = reference.previewTemporary ? safeTemporaryPreviewFile(reference.previewPath) : null; diagnostic.placeholderLayerIndex = layer.index; diagnostic.placeholderLayerName = layer.name; diagnostic.oldSourceId = oldSource ? oldSource.id : undefined; diagnostic.oldSourceType = sourceType(oldSource); layer.replaceSource(imported, false); if (!layer.source || layer.source.id !== imported.id || sourceType(layer.source) !== "FileSource") throw new Error("Layer source verification failed after replaceSource()."); layer.name = completedLayerName || imported.name; diagnostic.sourceReplaced = true; diagnostic.newSourceId = layer.source.id; diagnostic.newSourceType = sourceType(layer.source); diagnostic.overlayLayersRemoved = removeJobOverlays(target, reference.jobId); if (oldSource && sourceType(oldSource) === "SolidSource") { if (oldSource.usedIn && oldSource.usedIn.length === 0) { oldSource.remove(); diagnostic.solidRemoved = true; } else { diagnostic.solidRetainedBecauseUsed = true; } } else if (oldSource && reference.previewTemporary === true && sourceType(oldSource) === "FileSource") { if (oldSource.usedIn && oldSource.usedIn.length === 0) { oldSource.remove(); diagnostic.temporaryPreviewRemoved = true; if (temporaryPreviewFile && temporaryPreviewFile.exists) diagnostic.temporaryPreviewFileRemoved = temporaryPreviewFile.remove(); } else { diagnostic.temporaryPreviewRetainedBecauseUsed = true; } } app.endUndoGroup(); diagnostic.ok = true; return result(diagnostic); } catch (e) { try { app.endUndoGroup(); } catch (_) {} diagnostic.replaceSourceError = e && e.message ? e.message : String(e); return result(diagnostic); } },
    writeGenerationMetadata: function (reference, metadata) { try { var layer = findPlaceholderLayer(reference); if (!layer || !layer.source || layer.source.id !== reference.footageItemId) throw new Error("Generated layer reference changed before metadata could be written."); layer.comment = metadataText(metadata); return result(null); } catch (e) { return failure(e); } },
    getProjectFileContext: function () { try { var projectFile = app.project ? app.project.file : null; return result({ saved: Boolean(projectFile), projectFilePath: projectFile ? projectFile.fsName : null, projectDirectory: projectFile ? projectFile.parent.fsName : null, appDataPath: Folder.userData ? Folder.userData.fsName : null, tempPath: Folder.temp ? Folder.temp.fsName : null }); } catch (e) { return failure(e); } },
    revealFile: function (path) { try { var file = new File(path); if (!file.exists) throw new Error("File no longer exists: " + path); file.parent.execute(); return result(null); } catch (e) { return failure(e); } },
    revealFolder: function (path) { try { var file = new File(path); var folder = file.parent; if (!folder || !folder.exists) throw new Error("Output folder no longer exists: " + (folder ? folder.fsName : path)); folder.execute(); return result(null); } catch (e) { return failure(e); } },
    openFile: function (path) { try { var file = new File(path); if (!file.exists) throw new Error("File no longer exists: " + path); if (!file.execute()) throw new Error(file.error || "Could not open file: " + path); return result(null); } catch (e) { return failure(e); } },
    revealProjectItem: function (itemId) { try { var item = itemById(itemId); var selected = app.project.selection || []; for (var i = 0; i < selected.length; i++) selected[i].selected = false; item.selected = true; return result(null); } catch (e) { return failure(e); } },
    addProjectItemToActiveComposition: function (itemId) { try { var target = comp(); var item = itemById(itemId); for (var i = 1; i <= target.numLayers; i++) if (target.layer(i).source && target.layer(i).source.id === item.id) return result({ compositionId: target.id, layerIndex: target.layer(i).index, alreadyAdded: true }); var layer = target.layers.add(item); layer.startTime = target.time; layer.inPoint = target.time; return result({ compositionId: target.id, layerIndex: layer.index, alreadyAdded: false }); } catch (e) { return failure(e); } },
    addAllToActiveComposition: function (itemIds) { try { var added = [], skipped = []; for (var i = 0; i < itemIds.length; i++) { var parsed = JSON.parse(this.addProjectItemToActiveComposition(itemIds[i])); if (!parsed.ok) throw new Error(parsed.error); (parsed.value.alreadyAdded ? skipped : added).push(itemIds[i]); } return result({ added: added, skipped: skipped }); } catch (e) { return failure(e); } },
    createCompositionFromImage: function (itemId, duration) { try { var item = itemById(itemId); if (!(item instanceof FootageItem) || !(item.mainSource instanceof FileSource)) throw new Error("Image footage is unavailable."); var marker = "SnarkRoute sourceItemId=" + item.id; for (var i = 1; i <= app.project.numItems; i++) { var existing = app.project.item(i); if (existing instanceof CompItem && String(existing.comment || "").indexOf(marker) >= 0) return result({ compositionId: existing.id, layerIndex: existing.numLayers ? existing.layer(1).index : 0, reused: true }); } var frameRate = app.project.activeItem instanceof CompItem ? app.project.activeItem.frameRate : 30; var compItem = app.project.items.addComp(item.name, Math.max(1, item.width), Math.max(1, item.height), 1, Math.max(1 / frameRate, Number(duration) || 5), frameRate); compItem.comment = marker; var layer = compItem.layers.add(item); return result({ compositionId: compItem.id, layerIndex: layer.index, reused: false }); } catch (e) { return failure(e); } }
  };
}());

var SnarkRouteMCP = (function () {
  function errorDetails(error) { return { message: error && error.message ? String(error.message) : String(error), stack: error && error.stack ? String(error.stack) : undefined, line: error && error.line ? Number(error.line) : undefined, fileName: error && error.fileName ? String(error.fileName) : undefined }; }
  function text(value) { try { if (typeof value === "string") return value; return JSON.stringify(value); } catch (_) { return String(value); } }
  return {
    sessionInfo: function () { var p = app.project, f = p && p.file; return JSON.stringify({ appVersion: String(app.version || "unknown"), projectName: f ? f.name : "Untitled Project", projectPath: f ? f.fsName : null }); },
    execute: function (payload) {
      var started = new Date().getTime(), logs = [], undoStarted = false;
      var console = { log: function (v) { logs.push({ level: "log", message: text(v) }); }, warn: function (v) { logs.push({ level: "warn", message: text(v) }); }, error: function (v) { logs.push({ level: "error", message: text(v) }); } };
      try {
        if (payload.mode === "preview") return JSON.stringify({ ok: true, result: { preparedJsx: payload.code }, logs: logs, durationMs: new Date().getTime() - started });
        if (payload.undoGroup !== false) { app.beginUndoGroup(String(payload.undoGroup || "MCP: arbitrary JSX")); undoStarted = true; }
        var value;
        try { value = eval(String(payload.code)); }
        catch (first) { if (/return/i.test(String(first && first.message))) value = eval("(function(){\n" + String(payload.code) + "\n}).call(this)"); else throw first; }
        if (undoStarted) { app.endUndoGroup(); undoStarted = false; }
        return JSON.stringify({ ok: true, result: typeof value === "undefined" ? null : value, resultType: typeof value === "undefined" ? "undefined" : typeof value, logs: logs, durationMs: new Date().getTime() - started });
      } catch (error) {
        if (undoStarted) try { app.endUndoGroup(); } catch (_) {}
        return JSON.stringify({ ok: false, error: errorDetails(error), logs: logs, durationMs: new Date().getTime() - started });
      }
    }
  };
}());
